### ISSUE TITLE
HALP ITS ERROR

### ISSUE THREAD

**Issue by HertZxD** [timgrossmann/InstaPy#4972]
InstaPy Version: 0.6.2
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "C:/Users/ASUS/InstaPy"
Traceback (most recent call last):
  File "E:\python\Lib\site-packages\Instapy\InstaPy\quickstart.py", line 30, in <module>
    headless_browser=False)
  File "E:\python\Lib\site-packages\Instapy\InstaPy\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "E:\python\Lib\site-packages\Instapy\InstaPy\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "E:\python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "E:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "E:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "E:\python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "E:\python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

>>>

**Comment by ceribbo** [comment]
Same here!

**Comment by bvanhou** [comment]
Referencing, capabilities of your browser. What is your browser and driver versions? Firefox or Chrome?

**Comment by omerbadawy11** [comment]
i have the same issue

Traceback (most recent call last):
  File ".\Firstquickstart.py", line 21, in <module>
    headless_browser=False)
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\instapy.py", line 321, in __init__
    self.logger,
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 174, in __init__
    keep_alive=True)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by bvanhou** [comment]
Please refer to my comment above. This is not helpful

**Comment by omerbadawy11** [comment]
I apologize :), I'm using firefox for the bot and its the latest version, and my gecko is v0.24.0

**Comment by ceribbo** [comment]
Actually I solved the problem by manually downlaoding the geckdriver: instapy used to download a newer version of geckodriver, however it downloaded the 32bit version instead of the 64 (in my case). 
So the problem is the get_geckodriver() function that is downloading and setting the wrong version.

**Comment by omerbadawy11** [comment]
> Actually I solved the problem by manually downlaoding the geckdriver: instapy used to download a newer version of geckodriver, however it downloaded the 32bit version instead of the 64 (in my case).
> So the problem is the get_geckodriver() function that is downloading and setting the wrong version.

i tried to manually download but instapy replaces it, how do i force it o use 64 bit ?

**Comment by ceribbo** [comment]
I obviously also commented the get_geckodriver() function, otherwise it would have replace it every time, 
just put `#or get_geckodriver()` to comment it (line 110 in browser.py) and pass the `geckodriver_path` when creating an InstaPy session

**Comment by omerbadawy11** [comment]
I put the #or get_geckodriver() but how to i "pass the geckodriver_path when creating an InstaPy session"

**Comment by ceribbo** [comment]
when you create an InstaPy session like 
```
session = InstaPy(username=user, password=pss, geckodriver_path='C:\\User\...\assets\geckodriver')
session.login()
....
```

**Comment by omerbadawy11** [comment]
alright so instead i made my line 110    
 `driver_path = r'C:\Users\Omer\InstaPy\assets\geckodriver.exe' #or get_geckodriver()`

and now i get this:

```
Traceback (most recent call last):
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\util.py", line 1061, in get_relationship_counts
    "return window._sharedData.entry_data."
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 636, in execute_script
    'args': converted_args})['value']
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Omer\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: TypeError: window._sharedData.entry_data.ProfilePage[0].graphql is undefined


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Firstquickstart.py", line 52, in <module>
    session.like_by_tags(amount=35, use_smart_hashtags=True)
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\instapy.py", line 1928, in like_by_tags
    validation, details = self.validate_user_call(user_name)
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\instapy.py", line 1317, in validate_user_call
    self.logfolder,
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\util.py", line 207, in validate_username
    browser, username, logger
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\util.py", line 1069, in get_relationship_counts
    str(read_xpath(get_relationship_counts.__name__, "followers_count"))
  File "D:\InstaPy-0.6.2\InstaPy-0.6.2\instapy\util.py", line 1002, in format_number
    formatted_num = number.replace(",", "")
AttributeError: 'FirefoxWebElement' object has no attribute 'replace'
```
