### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Myloune** [timgrossmann/InstaPy#5155]
Since I launched the update of the module on my ubuntu it does not run anymore however the configuration is correct and well followed the tutorial for ubuntu version 64 bit

Here is the error message: pyton quick.py

`Traceback (most recent call last):
  File "quick.py", line 2, in <module>
    from instapy import InstaPy
  File "/home/test/InstaPy/instapy/__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "/home/test/InstaPy/instapy/instapy.py", line 105
    username: str = None,
            ^
SyntaxError: invalid syntax`

With the command: pyton3 quick.py
`InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/test/InstaPy"
Traceback (most recent call last):
  File "riri.py", line 14, in <module>
    headless_browser=False)
  File "/home/test/InstaPy/instapy/instapy.py", line 321, in __init__
    self.logger,
  File "/home/test/InstaPy/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities`

Thank you for helping me or finding a solution for my problem. I think this is due to the new version

**Comment by elijahhezekiah12** [comment]
You need to fix firefox. I had this problem need to make sure firefox is running or if you have not installed it on your server you should. 

Try pip3 install firefox 

I also had to download xquartz on my desktop 

Also if you are running ubuntu Headless should be = True.

**Comment by Myloune** [comment]
The problem is solved effectively it had to be activated on "True" before it was on "False"

But I encounter the same problem as #5145

`InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/test/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-10-18 08:40:39] [pizza.inc]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-10-18 08:40:39] [pizza.inc]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-10-18 08:40:53] [pizza.inc]  - Internet Connection Status: ok
INFO [2019-10-18 08:40:53] [pizza.inc]  - Current IP is "46.105.156.227" and it's from "France/FR"
INFO [2019-10-18 08:40:53] [pizza.inc]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram WebSite Status: Currently Up 
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Response Time: 38.289 ms 
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Reponse Code: 200
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Server Status: ok
INFO [2019-10-18 08:41:21] [pizza.inc]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-10-18 08:41:21] [pizza.inc]  - window.navigator.webdriver response: False
INFO [2019-10-18 08:41:21] [pizza.inc]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2019-10-18 08:42:16] [pizza.inc]  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2019-10-18 08:43:23] [pizza.inc]  Timed out with failure while explicitly waiting until visibility of element located!

ERROR [2019-10-18 08:43:34] [pizza.inc]  Error occurred while deleting cookies from web browser!
	b'Message: Tried to run command without establishing a connection\n'
Traceback (most recent call last):
  File "/home/test/InstaPy-new/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/home/test/InstaPy-new/instapy/instapy.py", line 412, in login
    self.bypass_security_challenge_using,
  File "/home/test/InstaPy-new/instapy/login_util.py", line 345, in login_user
    input_username = browser.find_element_by_xpath(input_username_XP)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/InstaPy-new/instapy/browser.py", line 167, in close_browser
    browser.delete_all_cookies()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection


INFO [2019-10-18 08:43:36] [pizza.inc]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 3.12 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-10-18 08:43:36] [pizza.inc]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "riri.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/test/InstaPy-new/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/home/test/InstaPy-new/instapy/instapy.py", line 412, in login
    self.bypass_security_challenge_using,
  File "/home/test/InstaPy-new/instapy/login_util.py", line 345, in login_user
    input_username = browser.find_element_by_xpath(input_username_XP)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette`

**Comment by Myloune** [comment]
The problem is solved effectively it had to be activated on "True" before it was on "False"

But I encounter the same problem as #5145

InstaPy Version: 0.6.4
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/home/test/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-10-18 08:40:39] [pizza.inc]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2019-10-18 08:40:39] [pizza.inc]  -- Connection Checklist [1/3] (Internet Connection Status)
INFO [2019-10-18 08:40:53] [pizza.inc]  - Internet Connection Status: ok
INFO [2019-10-18 08:40:53] [pizza.inc]  - Current IP is "46.105.156.227" and it's from "France/FR"
INFO [2019-10-18 08:40:53] [pizza.inc]  -- Connection Checklist [2/3] (Instagram Server Status)
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram WebSite Status: Currently Up 
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Response Time: 38.289 ms 
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Reponse Code: 200
INFO [2019-10-18 08:41:21] [pizza.inc]  - Instagram Server Status: ok
INFO [2019-10-18 08:41:21] [pizza.inc]  -- Connection Checklist [3/3] (Hide Selenium Extension)
INFO [2019-10-18 08:41:21] [pizza.inc]  - window.navigator.webdriver response: False
INFO [2019-10-18 08:41:21] [pizza.inc]  - Hide Selenium Extension: ok
Cookie file not found, creating cookie...
INFO [2019-10-18 08:42:16] [pizza.inc]  Timed out with failure while explicitly waiting until title contains 'Login' string!

INFO [2019-10-18 08:43:23] [pizza.inc]  Timed out with failure while explicitly waiting until visibility of element located!

ERROR [2019-10-18 08:43:34] [pizza.inc]  Error occurred while deleting cookies from web browser!
	b'Message: Tried to run command without establishing a connection\n'
Traceback (most recent call last):
  File "/home/test/InstaPy-new/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/home/test/InstaPy-new/instapy/instapy.py", line 412, in login
    self.bypass_security_challenge_using,
  File "/home/test/InstaPy-new/instapy/login_util.py", line 345, in login_user
    input_username = browser.find_element_by_xpath(input_username_XP)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/InstaPy-new/instapy/browser.py", line 167, in close_browser
    browser.delete_all_cookies()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 878, in delete_all_cookies
    self.execute(Command.DELETE_ALL_COOKIES)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection


INFO [2019-10-18 08:43:36] [pizza.inc]  Sessional Live Report:
	|> No any statistics to show


[Session lasted 3.12 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-10-18 08:43:36] [pizza.inc]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "riri.py", line 16, in <module>
    with smart_run(session):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/test/InstaPy-new/instapy/util.py", line 1839, in smart_run
    session.login()
  File "/home/test/InstaPy-new/instapy/instapy.py", line 412, in login
    self.bypass_security_challenge_using,
  File "/home/test/InstaPy-new/instapy/login_util.py", line 345, in login_user
    input_username = browser.find_element_by_xpath(input_username_XP)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

**Comment by digimix** [comment]
apt-get install firefox

**Comment by Myloune** [comment]
>  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
No any custom workspace provided.       ~using existing..
InstaPy Version: 0.6.6
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pipo/InstaPy"
Traceback (most recent call last):
  File "riri.py", line 20, in <module>
    headless_browser=False)
  File "/home/pipo/InstaPy-master/instapy/instapy.py", line 319, in __init__
    self.logger,
  File "/home/pipo/InstaPy-master/instapy/browser.py", line 114, in set_selenium_local_session
    options=firefox_options,
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process

I have the same problem after installing firefox

**Comment by josh-kea** [comment]
> apt-get install firefox

Mate, you are amazing! THIS WORKED !!!!!

**Comment by radgezito** [comment]
I have the same problem here, using 0.6.10.

Any solution?
